# -*- coding: utf-8 -*-
"""faq_chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2BAUQHGOQLMCNblNPZE9UWWZAuQgWZL
"""

faq = {
    "hello": "Hi! How can I help you today?",
    "hours": "Our working hours are 9am - 5pm, Monday to Friday.",
    "bye": "Goodbye! Have a nice day."
}

def chatbot():
    print("Welcome to FAQ Chatbot! Type 'exit' to quit.")
    while True:
        question = input("You: ").lower()
        if question == "exit":
            print("Chatbot: Goodbye!")
            break
        answer = faq.get(question, "Sorry, I don't understand that.")
        print("Chatbot:", answer)

if __name__ == "__main__":
    chatbot()